# Only master is affected
branches:
  only:
  - master

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install g++ 

script:
  - make && ./bin/hexibit_tests

after_success:
  - echo "The job was a success"

notifications:
  email:
    on_success: change
    on_failure: always
